# Assignment_2

## The provided data contains various details and attributes associated with used cars. The target variable, which is the central focus of analysis, is the price of the used cars, and it is measured in lakhs. The data in this dataset is tabular, with rows and columns, where each row represents a specific used car listing, and each column represents a particular attribute or feature of these cars. Features are Make and model of the car, Location or city of sale, Year of manufacture, Mileage, Odometer(kilometers driven), Fuel type (petrol or diesel), Transmission type (manual or automatic), Number of owners, Engine displacement, Engine horsepower, Number of seats, and Price when the car was new.

In [ ]:
import pandas as pd

# Load the dataset
file_path = '/content/drive/MyDrive/train.csv'
data = pd.read_csv(file_path)

# Display the first few rows
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

# A) Look for the missing values in all the columns and either impute them (replace with mean,median, or mode) or drop them. Justify your action for this task.

In [ ]:
# Checking for missing values
missing_values = data.isnull().sum()

# Display missing values count
missing_values

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

In [ ]:
import numpy as np

In [ ]:
# Importing numpy for NaN representation
import numpy as np

# replace 'null' with np.nan before conversion
data['Power'] = data['Power'].str.replace(' bhp', '').replace('null', np.nan).astype(float)

# Re-imputing missing values with median
data['Mileage'].fillna(data['Mileage'].median(), inplace=True)
data['Engine'].fillna(data['Engine'].median(), inplace=True)
data['Power'].fillna(data['Power'].median(), inplace=True)
data['Seats'].fillna(data['Seats'].median(), inplace=True)

# Verify if the missing values are imputed
data.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 0
Engine                  0
Power                   0
Seats                   0
New_Price            5032
Price                   0
dtype: int64

# B)Remove the units from some of the attributes and only keep the numerical values (for example remove kmpl from “Mileage”, CC from “Engine”, bhp from “Power”, and lakh from“New_price”).

In [ ]:
#  'New_Price' contains values in 'Lakh', we will also convert these values to the same scale as 'Price'

data['New_Price'] = data['New_Price'].str.extract('(\d+\.\d+|\d+)').astype(float)

# Display the first few rows to confirm changes happened
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.19,1199.0,88.70,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,NaN,3.50

# C)Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot encoded value.

In [ ]:
import pandas as pd
# One-hot encoding the categorical variables 'Fuel_Type' and 'Transmission'
data_encoded = pd.get_dummies(data, columns=['Fuel_Type', 'Transmission'])
data_encoded.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,1,0,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,0,0,1,0,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,1,0,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,1,0,0,1,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,1,0,0,0,1

# D)  Create one more feature and add this column to the dataset. For example, you can calculate the current age of the car by subtracting “Year” value from the current year

In [ ]:
# Calculating the current age of the car from the 'Year' column
current_year = 2024
data_encoded['Car_Age'] = current_year - data_encoded['Year']

# Display the first few rows to confirm
data_encoded.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,1,0,0,0,1,9
1,2,Honda Jazz V,Chennai,2011,46000,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,0,0,1,0,1,13
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,1,0,0,0,1,12
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,1,0,0,1,0,11
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,1,0,0,0,1,11

# E) Perform select, filter, rename, mutate, arrange and summarize with group by operations (or their equivalent operations in python) on this dataset

In [ ]:
#  Selecting a subset of columns
selected_columns = data_encoded[['Location', 'Year', 'Kilometers_Driven', 'Fuel_Type_Diesel', 'Transmission_Automatic', 'Price', 'Car_Age']]

# Filtering cars older than 10 years
filtered_data = selected_columns[selected_columns['Car_Age'] > 10]

#  Renaming 'Kilometers_Driven' to 'KMs_Driven'
renamed_data = filtered_data.rename(columns={'Kilometers_Driven': 'KMs_Driven'})

# Adding a new column 'Price_Per_Year' as Price divided by Car_Age
renamed_data['Price_Per_Year'] = renamed_data['Price'] / renamed_data['Car_Age']

# Sorting the data by 'Price' in descending order
arranged_data = renamed_data.sort_values(by='Price', ascending=False)

#  Calculating average price and average KMs driven by location
summary = arranged_data.groupby('Location').agg(Avg_Price=('Price', 'mean'), Avg_KMs_Driven=('KMs_Driven', 'mean')).reset_index()

# Displaying the first few rows of the summary data
summary.head()

     Location  Avg_Price  Avg_KMs_Driven
0   Ahmedabad   6.465455    63241.505051
1   Bangalore   9.200110    69368.480663
2     Chennai   5.415571    93050.782007
3  Coimbatore   9.514062    65551.226562
4       Delhi   7.849623    67651.777358